#!/bin/ksh
 
read ip?"Please provide filer IP : "
connection="ssh user@"$ip""

show_volumes(){
$connection 'vol show'
}
clean(){
show_volume | egrep "hana_data_|hana_log_|usr_sap_|sapdb_|sapmnt_" | awk '{print$2}' > volumes.txt

for i in cat volumes.txt
do
        $connection volume offline -vserver vserver-data -volume $i -f ; $connection volume delete -vserver vserver-data -volume $i
done

rm volumes.txt
}
hdb(){
    read instance_number?"Please provide instance number for HDB [hd1 - hd9] : "
    case $instance_number in
        "hd1") $connection vol create -vserver vserver-data -volume hana_data -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data ; $connection volume modify -vserver vserver-data -volume hana_data -policy vol_critical ; $connection vol create -vserver vserver-data -volume hana_data_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_data_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log ; $connection volume modify -vserver vserver-data -volume hana_log -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_log_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        "hd2") $connection vol create -vserver vserver-data -volume hana_data -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data ; $connection volume modify -vserver vserver-data -volume hana_data -policy vol_critical ; $connection vol create -vserver vserver-data -volume hana_data_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_data_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log ; $connection volume modify -vserver vserver-data -volume hana_log -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_log_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        "hd3") $connection vol create -vserver vserver-data -volume hana_data -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data ; $connection volume modify -vserver vserver-data -volume hana_data -policy vol_critical ; $connection vol create -vserver vserver-data -volume hana_data_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_data_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log ; $connection volume modify -vserver vserver-data -volume hana_log -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_log_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        "hd4") $connection vol create -vserver vserver-data -volume hana_data -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data ; $connection volume modify -vserver vserver-data -volume hana_data -policy vol_critical ; $connection vol create -vserver vserver-data -volume hana_data_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_data_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log ; $connection volume modify -vserver vserver-data -volume hana_log -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_log_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        "hd5") $connection vol create -vserver vserver-data -volume hana_data -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data ; $connection volume modify -vserver vserver-data -volume hana_data -policy vol_critical ; $connection vol create -vserver vserver-data -volume hana_data_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_data_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log ; $connection volume modify -vserver vserver-data -volume hana_log -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_log_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        "hd6") $connection vol create -vserver vserver-data -volume hana_data -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data ; $connection volume modify -vserver vserver-data -volume hana_data -policy vol_critical ; $connection vol create -vserver vserver-data -volume hana_data_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_data_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log ; $connection volume modify -vserver vserver-data -volume hana_log -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_log_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        "hd7") $connection vol create -vserver vserver-data -volume hana_data -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data ; $connection volume modify -vserver vserver-data -volume hana_data -policy vol_critical ; $connection vol create -vserver vserver-data -volume hana_data_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_data_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log ; $connection volume modify -vserver vserver-data -volume hana_log -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_log_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        "hd8") $connection vol create -vserver vserver-data -volume hana_data -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data ; $connection volume modify -vserver vserver-data -volume hana_data -policy vol_critical ; $connection vol create -vserver vserver-data -volume hana_data_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_data_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log ; $connection volume modify -vserver vserver-data -volume hana_log -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_log_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        "hd9") $connection vol create -vserver vserver-data -volume hana_data -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data ; $connection volume modify -vserver vserver-data -volume hana_data -policy vol_critical ; $connection vol create -vserver vserver-data -volume hana_data_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/hana_data_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_data_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log ; $connection volume modify -vserver vserver-data -volume hana_log -policy vol_critical; $connection vol create -vserver vserver-data -volume hana_log_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/hana_log_$instance_number ; $connection volume modify -vserver vserver-data -volume hana_log_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        *) echo "You choose bad action"
    esac
}
s4hana(){
    read instance_number?"Please provide instance number for S4HANA [sf1 - sf9] : "
    case $instance_number in
        "sf1") $connection vol create -vserver vserver-data -volume sapmnt -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt ; $connection volume modify -vserver vserver-data -volume sapmnt -policy vol_critical; $connection vol create -vserver vserver-data -volume sapmnt_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt_$instance_number ; $connection volume modify -vserver vserver-data -volume sapmnt_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        "sf2") $connection vol create -vserver vserver-data -volume sapmnt -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt ; $connection volume modify -vserver vserver-data -volume sapmnt -policy vol_critical; $connection vol create -vserver vserver-data -volume sapmnt_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt_$instance_number ; $connection volume modify -vserver vserver-data -volume sapmnt_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        "sf3") $connection vol create -vserver vserver-data -volume sapmnt -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt ; $connection volume modify -vserver vserver-data -volume sapmnt -policy vol_critical; $connection vol create -vserver vserver-data -volume sapmnt_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt_$instance_number ; $connection volume modify -vserver vserver-data -volume sapmnt_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        "sf4") $connection vol create -vserver vserver-data -volume sapmnt -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt ; $connection volume modify -vserver vserver-data -volume sapmnt -policy vol_critical; $connection vol create -vserver vserver-data -volume sapmnt_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt_$instance_number ; $connection volume modify -vserver vserver-data -volume sapmnt_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        "sf5") $connection vol create -vserver vserver-data -volume sapmnt -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt ; $connection volume modify -vserver vserver-data -volume sapmnt -policy vol_critical; $connection vol create -vserver vserver-data -volume sapmnt_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt_$instance_number ; $connection volume modify -vserver vserver-data -volume sapmnt_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        "sf6") $connection vol create -vserver vserver-data -volume sapmnt -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt ; $connection volume modify -vserver vserver-data -volume sapmnt -policy vol_critical; $connection vol create -vserver vserver-data -volume sapmnt_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt_$instance_number ; $connection volume modify -vserver vserver-data -volume sapmnt_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        "sf7") $connection vol create -vserver vserver-data -volume sapmnt -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt ; $connection volume modify -vserver vserver-data -volume sapmnt -policy vol_critical; $connection vol create -vserver vserver-data -volume sapmnt_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt_$instance_number ; $connection volume modify -vserver vserver-data -volume sapmnt_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        "sf8") $connection vol create -vserver vserver-data -volume sapmnt -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt ; $connection volume modify -vserver vserver-data -volume sapmnt -policy vol_critical; $connection vol create -vserver vserver-data -volume sapmnt_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt_$instance_number ; $connection volume modify -vserver vserver-data -volume sapmnt_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        "sf9") $connection vol create -vserver vserver-data -volume sapmnt -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt ; $connection volume modify -vserver vserver-data -volume sapmnt -policy vol_critical; $connection vol create -vserver vserver-data -volume sapmnt_$instance_number -aggregate aggr1 -size 100GB -junction-path /vserver-data/sapmnt_$instance_number ; $connection volume modify -vserver vserver-data -volume sapmnt_$instance_number -policy vol_critical; $connection vol create -vserver vserver-data -volume usr_sap -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap ; $connection volume modify -vserver vserver-data -volume usr_sap -policy vol_critical ; $connection vol create -vserver vserver-data -volume usr_sap_$instance_number -aggregate aggr1 -size 300GB -junction-path /vserver-data/usr_sap_$instance_number ; $connection volume modify -vserver vserver-data -volume usr_sap_$instance_number -policy vol_critical;;
        *) echo "You choose bad action"
    esac
}

if [ $# = 0 ]; then
        echo "\t \t \t \t \t!IMPORTANT!"
#        echo "You forgot to add volume as first argument, or show_volume to show all volumes on filer, or clean to clean whole filer"
        echo "Please add as first argument : \n show_volumes - check all volumes in filer, \n HDB - add required volumes for HanaDB, \n S4HANA - add required volumes for S4HANA, \n clean - clean all hana_data_|hana_log_|usr_sap_|sapdb_|sapmnt_ volumens, \n type volume - you can add or remove this volume in filer"
        echo "\t \t \t \t \t!IMPORTANT!"

elif [ $1 == "show_volumes" ];then
        show_volumes
elif [ $1 == "clean" ]; then
        clean
elif [ $1 == "HDB" ]; then
        hdb
elif [ $1 == "S4HANA" ]; then
        s4hana
else
        read action?"Provide action you want to perform (Delete|Add) : "
        case $action in
                "Delete") $connection volume offline -vserver vserver-data -volume $1 -f ; $connection volume delete -vserver vserver-data -volume $1 ;;
                "Add") read capacity?"Provide capacity for volume $1: "
                       $connection vol create -vserver vserver-data -volume $1 -aggregate aggr1 -size "$capacity"GB -junction-path /vserver-data/$1 ; $connection volume modify -vserver vserver-data -volume $1 -policy vol_critical ;;
                *) echo "You choose bad action"
esac

fi
